version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sop.ts
      POSTGRES_DB: Gen_DB
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: "postgresql://admin:sop.ts@127.0.0.1:5432/Gen_DB"

#  nginx:
#    image: nginx:1.15-alpine
#    restart: unless-stopped
#    volumes:
#      - ./nginx/:/etc/nginx/conf.d
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - backend

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: